### DISCUSSION TITLE
Add app filter to control which apps' lineage is extracted.

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler-spyglass#67] [Ideas]
A new section in the config file:

```yaml
ButlerSpyglass:
  ...
  # Filter out a selection of apps for which lineage and/or load scripts should be extracted.
  # Filters are additive.
  # If no filters are specified lineage/script will be extracted for all apps in the Sense server.
  appFilter:                        
    appNameExact:                   # Apps for which lineage/script should be extract. Exact matches are done on app name. 
      - Name1
      - name2
    appId:                          # App IDs for which lineage/script should be extracted.
      - ID1
      - ID2
    appTag:                         # Lineage/script will be extracted for apps having these tags set.
      - Tag1
      - Tag2
```
